label define states2 1 `"AL"', modify
label define states2 2 `"AK"', modify
label define states2 4 `"AZ"', modify
label define states2 5 `"AR"', modify
label define states2 6 `"CA"', modify
label define states2 8 `"CO"', modify
label define states2 9 `"CT"', modify
label define states2 10 `"DE"', modify
label define states2 11 `"DC"', modify
label define states2 12 `"FL"', modify
label define states2 13 `"GA"', modify
label define states2 15 `"HI"', modify
label define states2 16 `"ID"', modify
label define states2 17 `"IL"', modify
label define states2 18 `"IN"', modify
label define states2 19 `"IA"', modify
label define states2 20 `"KS"', modify
label define states2 21 `"KY"', modify
label define states2 22 `"LA"', modify
label define states2 23 `"ME"', modify
label define states2 24 `"MD"', modify
label define states2 25 `"MA"', modify
label define states2 26 `"MI"', modify
label define states2 27 `"MN"', modify
label define states2 28 `"MS"', modify
label define states2 29 `"MO"', modify
label define states2 30 `"MT"', modify
label define states2 31 `"NE"', modify
label define states2 32 `"NV"', modify
label define states2 33 `"NH"', modify
label define states2 34 `"NJ"', modify
label define states2 35 `"NM"', modify
label define states2 36 `"NY"', modify
label define states2 37 `"NC"', modify
label define states2 38 `"ND"', modify
label define states2 39 `"OH"', modify
label define states2 40 `"OK"', modify
label define states2 41 `"OR"', modify
label define states2 42 `"PA"', modify
label define states2 44 `"RI"', modify
label define states2 45 `"SC"', modify
label define states2 46 `"SD"', modify
label define states2 47 `"TN"', modify
label define states2 48 `"TX"', modify
label define states2 49 `"UT"', modify
label define states2 50 `"VT"', modify
label define states2 51 `"VA"', modify
label define states2 53 `"WA"', modify
label define states2 54 `"WV"', modify
label define states2 55 `"WI"', modify
label define states2 56 `"WY"', modify
label define states2 60 `"AS"', modify
label define states2 64 `"FM"', modify
label define states2 66 `"GU"', modify
label define states2 68 `"MH"', modify
label define states2 69 `"MP"', modify
label define states2 70 `"PW"', modify
label define states2 72 `"PR"', modify
label define states2 74 `"UM"', modify
label define states2 78 `"VI"', modify
